#!/bin/bash
./retcombined | egrep "###|RetInput|retResponse|End.*POST" | sed -e "s/^[0-9]//" | sed -e "s/^[0-9]//" | sed -e "s/^[0-9]//" | sed -e "s/^)//" | sed -e "s/\.[0-9][0-9][0-9]//" | sed -e "s/#/ /g"

